version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - 54320:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: admin
      POSTGRES_DB: test_db
    restart: always
    networks:
      - frontend
  app:
#    build: .
    image: driver220v/shortner:latest
    volumes:
      - ./configs/:/app/configs/
    container_name: shortner
    ports:
      - 8000:8080
    depends_on:
      - db
    entrypoint:
      ./out/exec
    networks:
      - frontend
    restart: always

networks:
  frontend:
    driver: bridge
